name: dapp
description: Example application to create a mobile dapp
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

  # WalletConnect
  ensemble_walletconnect:
    path: ../../

  # Algorand
  algorand_dart: 1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
