name: parsejs_null_safety
version: 2.0.4
description: A robust JavaScript parser for Dart with full null safety support. This package provides a complete JavaScript parsing solution that generates Abstract Syntax Trees (ASTs) for JavaScript code, enabling code analysis, transformation, and compilation tools.

homepage: https://ensembleui.com
repository: https://github.com/EnsembleUI/ensemble/tree/main/packages/parsejs_null_safety
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://pub.dev/documentation/parsejs_null_safety

topics:
  - javascript
  - parser
  - ast
  - compiler
  - language

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  unicode: '>=0.0.8 <1.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
