import 'dart:io';

import 'package:ensemble_test_runner/models/ensemble_test_models.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Temporarily wires [appDir] to run declarative YAML tests, then restores files.
class YamlTestAppPatcher {
  YamlTestAppPatcher(String appDir) : appDir = p.normalize(p.absolute(appDir));

  final String appDir;

  static const testEntryRelativePath = 'test/ensemble_tests.dart';
  static const integrationTestEntryRelativePath =
      'integration_test/ensemble_tests.dart';
  static String testsAssetLineFor(String testsDirRelative) =>
      '    - ${_withTrailingSlash(testsDirRelative)}';

  /// Firebase 12 / current Ensemble plugins require iOS 15+.
  static const minIntegrationIosDeploymentTarget = '15.0';

  /// Legacy CLI stub without module bootstrap.
  static const legacyTestEntryContents = '''
// Generated by ensemble_test_runner — run `dart run ensemble_test_runner:ensemble_test`.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';

void main() => runEnsembleYamlTests();
''';

  static String testEntryContentsFor(String packageName) => '''
// Generated by ensemble_test_runner — customize bootstrap here.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';
import 'package:$packageName/generated/ensemble_modules.dart';

Future<void> main() async {
  await runEnsembleYamlTests(
    bootstrap: () => EnsembleModules().init(),
  );
}
''';

  static String integrationTestEntryContentsFor(String packageName) => '''
// Generated by ensemble_test_runner — customize bootstrap here.
import 'package:ensemble_test_runner/entry/ensemble_integration_test_entry.dart';
import 'package:$packageName/generated/ensemble_modules.dart';

Future<void> main() async {
  await runEnsembleIntegrationYamlTests(
    bootstrap: () => EnsembleModules().init(),
  );
}
''';

  /// @deprecated Use [testEntryContentsFor].
  static String get testEntryContents =>
      testEntryContentsFor('your_app_package');

  final Map<String, String> _backups = {};
  final Set<String> _createdPaths = {};
  bool _enabled = false;
  bool _removeTestEntryOnRestore = false;
  bool _pubspecChanged = false;
  ExecutionMode _mode = ExecutionMode.widget;

  bool get pubspecChanged => _pubspecChanged;

  String? get testsDirRelative => _testsDirRelative;

  String? get testsDirPath {
    final relative = testsDirRelative;
    if (relative == null) return null;
    return p.join(appDir, relative);
  }

  bool get hasTestYamlOnDisk {
    final testsDir = testsDirRelative;
    return testsDir != null && _hasTestYamlOnDisk(testsDir);
  }

  String get _pubspecPath => p.join(appDir, 'pubspec.yaml');
  String get activeEntryRelativePath => _mode == ExecutionMode.integration
      ? integrationTestEntryRelativePath
      : testEntryRelativePath;
  String get _testEntryPath => p.join(appDir, activeEntryRelativePath);
  String get _testDirPath => p.dirname(_testEntryPath);
  String get _ensembleConfigPath =>
      p.join(appDir, 'ensemble', 'ensemble-config.yaml');

  /// Temporarily wires the app for YAML tests.
  ///
  /// Validates prerequisites before mutating files. On any failure, every
  /// touched file is restored and created files are deleted — even when
  /// [enable] never reached the success path.
  void enable({
    ExecutionMode mode = ExecutionMode.widget,
    bool fixIosDeploymentTarget = false,
  }) {
    if (_enabled) return;
    _mode = mode;

    try {
      _validateBeforeMutation(mode: mode);

      _backup(_pubspecPath);
      _backup(_testEntryPath, optional: true);

      final pubspec = File(_pubspecPath).readAsStringSync();
      final activated = _activatePubspec(pubspec, mode: mode);
      _pubspecChanged = activated != pubspec;
      if (_pubspecChanged) {
        File(_pubspecPath).writeAsStringSync(activated);
      }

      final testEntry = File(_testEntryPath);
      final testEntryExisted = testEntry.existsSync();
      _removeTestEntryOnRestore = !testEntryExisted;

      if (!testEntryExisted) {
        Directory(_testDirPath).createSync(recursive: true);
        testEntry.writeAsStringSync(mode == ExecutionMode.integration
            ? integrationTestEntryContentsFor(_readPackageName())
            : testEntryContentsFor(_readPackageName()));
        _createdPaths.add(_testEntryPath);
      } else if (mode == ExecutionMode.widget &&
          testEntry.readAsStringSync().trim() ==
              legacyTestEntryContents.trim()) {
        final upgraded = testEntryContentsFor(_readPackageName());
        testEntry.writeAsStringSync(upgraded);
        _backups[_testEntryPath] = upgraded;
        _removeTestEntryOnRestore = false;
      }

      if (mode == ExecutionMode.integration) {
        if (fixIosDeploymentTarget) {
          _ensureIosDeploymentTarget();
        } else {
          _requireIosDeploymentTarget();
        }
      }

      _enabled = true;
    } catch (_) {
      _rollbackMutations();
      rethrow;
    }
  }

  /// Restores every file touched by a successful [enable].
  void restore() {
    if (!_enabled) return;
    _rollbackMutations();
  }

  /// Rolls back backups and deletes created files regardless of [_enabled].
  void _rollbackMutations() {
    if (_removeTestEntryOnRestore || _createdPaths.contains(_testEntryPath)) {
      _deleteTestEntry();
    } else {
      _restore(_testEntryPath);
    }
    _restore(_pubspecPath);
    for (final path in _backups.keys.toList()) {
      if (path == _pubspecPath || path == _testEntryPath) continue;
      _restore(path);
    }
    for (final path in _createdPaths) {
      if (path == _testEntryPath) continue;
      final file = File(path);
      if (file.existsSync()) file.deleteSync();
    }

    _backups.clear();
    _createdPaths.clear();
    _enabled = false;
    _removeTestEntryOnRestore = false;
    _pubspecChanged = false;
    _mode = ExecutionMode.widget;
  }

  void _validateBeforeMutation({required ExecutionMode mode}) {
    final testEntry = File(_testEntryPath);
    if (!testEntry.existsSync()) return;

    final content = testEntry.readAsStringSync();
    if (mode == ExecutionMode.widget &&
        content.trim() == legacyTestEntryContents.trim()) {
      return;
    }

    final expectedCall = mode == ExecutionMode.integration
        ? 'runEnsembleIntegrationYamlTests'
        : 'runEnsembleYamlTests';
    if (!entryPointCallsFunction(content, expectedCall)) {
      throw StateError(
        '$activeEntryRelativePath must call $expectedCall().',
      );
    }
  }

  /// Whether [source] invokes [functionName] outside comments.
  static bool entryPointCallsFunction(String source, String functionName) {
    final stripped = stripDartComments(source);
    return RegExp('\\b${RegExp.escape(functionName)}\\s*\\(')
        .hasMatch(stripped);
  }

  /// Removes `//` and `/* */` comments for entry-point validation.
  static String stripDartComments(String source) {
    final buffer = StringBuffer();
    var i = 0;
    while (i < source.length) {
      if (i + 1 < source.length && source[i] == '/' && source[i + 1] == '/') {
        i += 2;
        while (i < source.length && source[i] != '\n') {
          i++;
        }
        continue;
      }
      if (i + 1 < source.length && source[i] == '/' && source[i + 1] == '*') {
        i += 2;
        while (i + 1 < source.length &&
            !(source[i] == '*' && source[i + 1] == '/')) {
          i++;
        }
        i = i + 2 < source.length ? i + 2 : source.length;
        continue;
      }
      if (source[i] == "'" || source[i] == '"') {
        final quote = source[i];
        buffer.write(quote);
        i++;
        while (i < source.length) {
          final ch = source[i];
          buffer.write(ch);
          if (ch == '\\' && i + 1 < source.length) {
            buffer.write(source[i + 1]);
            i += 2;
            continue;
          }
          if (ch == quote) {
            i++;
            break;
          }
          i++;
        }
        continue;
      }
      buffer.write(source[i]);
      i++;
    }
    return buffer.toString();
  }

  void _backup(String path, {bool optional = false}) {
    if (_backups.containsKey(path)) return;
    final file = File(path);
    if (!file.existsSync()) {
      if (!optional) {
        throw StateError('Expected file not found: $path');
      }
      _backups[path] = '';
      return;
    }
    _backups[path] = file.readAsStringSync();
  }

  void _restore(String path) {
    final backup = _backups[path];
    if (backup == null) return;
    if (backup.isEmpty) {
      final file = File(path);
      if (file.existsSync()) file.deleteSync();
      return;
    }
    File(path).writeAsStringSync(backup);
  }

  String _readPackageName() {
    final content = File(_pubspecPath).readAsStringSync();
    final match =
        RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(content);
    if (match == null) {
      throw StateError('Could not read package name from pubspec.yaml');
    }
    return match.group(1)!;
  }

  void _deleteTestEntry() {
    final file = File(_testEntryPath);
    if (file.existsSync()) {
      file.deleteSync();
    }
    final testDir = Directory(_testDirPath);
    if (testDir.existsSync() && testDir.listSync().isEmpty) {
      testDir.deleteSync();
    }
  }

  TimerRewriteConfig get timerRewriteConfig => _readTimerRewriteConfig();

  bool get hasTimerRewrites => timerRewriteConfig.enabled;

  void rewriteTimersIn(String targetAppDir) {
    final config = _readTimerRewriteConfig();
    if (!config.enabled) return;

    final testsDir = testsDirRelative;
    if (testsDir == null) return;
    final screensDir = Directory(
      p.join(
        p.normalize(p.absolute(targetAppDir)),
        p.dirname(_withoutTrailingSlash(testsDir)),
        'screens',
      ),
    );
    if (!screensDir.existsSync()) return;

    for (final entity in screensDir.listSync(recursive: true)) {
      if (entity is! File || !entity.path.endsWith('.yaml')) continue;
      final original = entity.readAsStringSync();
      final rewritten = _capTimerValues(original, config);
      if (rewritten == original) continue;
      entity.writeAsStringSync(rewritten);
    }
  }

  TimerRewriteConfig _readTimerRewriteConfig() {
    final path =
        testsDirPath == null ? null : p.join(testsDirPath!, 'config.yaml');
    if (path == null) return const TimerRewriteConfig();

    final file = File(path);
    if (!file.existsSync()) return const TimerRewriteConfig();
    final dynamic config = loadYaml(file.readAsStringSync());
    if (config is! YamlMap) return const TimerRewriteConfig();
    final timers = config['timers'];
    if (timers is! YamlMap) return const TimerRewriteConfig();
    return TimerRewriteConfig(
      enabled: timers['enabled'] == true,
      maxStartAfterSeconds: _parseNonNegativeInt(
        timers['maxStartAfterSeconds'],
        fallback: 1,
      ),
      maxRepeatIntervalSeconds: _parseNonNegativeInt(
        timers['maxRepeatIntervalSeconds'],
        fallback: 1,
      ),
    );
  }

  static String _capTimerValues(
    String content,
    TimerRewriteConfig config,
  ) {
    final startAfter =
        RegExp(r'^(\s*startAfter:\s*)(\d+)(\s*)$', multiLine: true);
    final repeatInterval =
        RegExp(r'^(\s*repeatInterval:\s*)(\d+)(\s*)$', multiLine: true);
    return content
        .replaceAllMapped(
          startAfter,
          (match) => _capTimerLine(match, config.maxStartAfterSeconds),
        )
        .replaceAllMapped(
          repeatInterval,
          (match) => _capTimerLine(match, config.maxRepeatIntervalSeconds),
        );
  }

  static String _capTimerLine(Match match, int maxValue) {
    final current = int.parse(match.group(2)!);
    if (current <= maxValue) return match.group(0)!;
    return '${match.group(1)}$maxValue${match.group(3)}';
  }

  static int _parseNonNegativeInt(dynamic value, {required int fallback}) {
    if (value == null) return fallback;
    final parsed = value is int ? value : int.tryParse(value.toString());
    if (parsed == null || parsed < 0) return fallback;
    return parsed;
  }

  String _activatePubspec(
    String content, {
    required ExecutionMode mode,
  }) {
    var activated = content;
    final testsDir = testsDirRelative;
    if (testsDir != null && _hasTestYamlOnDisk(testsDir)) {
      activated =
          _activateTestAssets(activated, testsDir, _testsAssetLines(testsDir));
    }
    if (mode == ExecutionMode.integration) {
      activated = _activateIntegrationDependency(activated);
    }
    return activated;
  }

  /// Raises iOS deployment files to [minIntegrationIosDeploymentTarget].
  ///
  /// Used by `ensemble_test --doctor --fix`. Integration [enable] does not
  /// rewrite these by default; pass [fixIosDeploymentTarget] to opt in.
  void applyIosDeploymentTargetFix() {
    _ensureIosDeploymentTarget();
  }

  void _requireIosDeploymentTarget() {
    final message = iosDeploymentTargetRequirementMessage(appDir);
    if (message != null) {
      throw StateError(message);
    }
  }

  /// Returns an actionable error when iOS deployment is below the minimum,
  /// or null when the project is OK / has no iOS folder.
  static String? iosDeploymentTargetRequirementMessage(String appDir) {
    final min = minIntegrationIosDeploymentTarget;
    final iosDir = Directory(p.join(appDir, 'ios'));
    if (!iosDir.existsSync()) return null;

    final podfile = File(p.join(appDir, 'ios', 'Podfile'));
    if (!podfile.existsSync()) {
      return 'ios/Podfile is missing; CocoaPods will default to iOS 13.0. '
          'Firebase plugins require $min. Set `platform :ios, \'$min\'` in '
          'ios/Podfile, or run `dart run ensemble_test_runner:ensemble_test '
          '--doctor --fix`.';
    }
    final content = podfile.readAsStringSync();
    final match = RegExp(
      r'''^#?\s*platform\s*:ios\s*,\s*['"]([0-9.]+)['"]''',
      multiLine: true,
    ).firstMatch(content);
    final version = match?.group(1);
    final commented =
        match != null && match.group(0)!.trimLeft().startsWith('#');
    if (version == null ||
        commented ||
        iosVersionLessThan(version, min)) {
      final current =
          version == null || commented ? 'unset (defaults to 13.0)' : version;
      return 'iOS deployment target is $current; Firebase plugins require $min. '
          'Set `platform :ios, \'$min\'` in ios/Podfile (and matching '
          'IPHONEOS_DEPLOYMENT_TARGET), or run '
          '`dart run ensemble_test_runner:ensemble_test --doctor --fix`.';
    }
    return null;
  }

  void _ensureIosDeploymentTarget() {
    final podfile = File(p.join(appDir, 'ios', 'Podfile'));
    if (podfile.existsSync()) {
      _rewriteIfChanged(podfile, raisePodfilePlatform);
    }
    final pbxproj = File(
      p.join(appDir, 'ios', 'Runner.xcodeproj', 'project.pbxproj'),
    );
    if (pbxproj.existsSync()) {
      _rewriteIfChanged(pbxproj, raisePbxprojDeploymentTarget);
    }
    final frameworkPlist = File(
      p.join(appDir, 'ios', 'Flutter', 'AppFrameworkInfo.plist'),
    );
    if (frameworkPlist.existsSync()) {
      _rewriteIfChanged(frameworkPlist, raisePlistMinimumOsVersion);
    }
  }

  void _rewriteIfChanged(File file, String Function(String content) rewrite) {
    final original = file.readAsStringSync();
    final updated = rewrite(original);
    if (updated == original) return;
    _backup(file.path);
    file.writeAsStringSync(updated);
  }

  /// Uncomments or raises `platform :ios` so CocoaPods accepts Firebase 12.
  static String raisePodfilePlatform(
    String content, {
    String min = minIntegrationIosDeploymentTarget,
  }) {
    final platformLine = RegExp(
      r'''^#?\s*platform\s*:ios\s*,\s*['"]([0-9.]+)['"][ \t]*$''',
      multiLine: true,
    );
    final match = platformLine.firstMatch(content);
    if (match == null) {
      return "platform :ios, '$min'\n\n$content";
    }
    final current = match.group(1)!;
    final target = iosVersionLessThan(current, min) ? min : current;
    final replacement = "platform :ios, '$target'";
    if (match.group(0) == replacement) return content;
    return content.replaceFirst(match.group(0)!, replacement);
  }

  static String raisePbxprojDeploymentTarget(
    String content, {
    String min = minIntegrationIosDeploymentTarget,
  }) {
    return content.replaceAllMapped(
      RegExp(r'IPHONEOS_DEPLOYMENT_TARGET = ([0-9.]+);'),
      (match) {
        final current = match.group(1)!;
        if (!iosVersionLessThan(current, min)) return match.group(0)!;
        return 'IPHONEOS_DEPLOYMENT_TARGET = $min;';
      },
    );
  }

  static String raisePlistMinimumOsVersion(
    String content, {
    String min = minIntegrationIosDeploymentTarget,
  }) {
    return content.replaceAllMapped(
      RegExp(
        r'(<key>MinimumOSVersion</key>\s*<string>)([0-9.]+)(</string>)',
      ),
      (match) {
        final current = match.group(2)!;
        if (!iosVersionLessThan(current, min)) return match.group(0)!;
        return '${match.group(1)}$min${match.group(3)}';
      },
    );
  }

  static bool iosVersionLessThan(String current, String minimum) {
    List<int> parts(String value) =>
        value.split('.').map((part) => int.tryParse(part) ?? 0).toList();
    final left = parts(current);
    final right = parts(minimum);
    final length = left.length > right.length ? left.length : right.length;
    for (var i = 0; i < length; i++) {
      final a = i < left.length ? left[i] : 0;
      final b = i < right.length ? right[i] : 0;
      if (a != b) return a < b;
    }
    return false;
  }

  static String _activateIntegrationDependency(String content) {
    if (RegExp(r'^\s{2}integration_test\s*:', multiLine: true)
        .hasMatch(content)) {
      return content;
    }
    const dependency = '  integration_test:\n    sdk: flutter\n';
    const marker = 'dev_dependencies:\n';
    if (content.contains(marker)) {
      return content.replaceFirst(marker, '$marker$dependency');
    }
    final flutterIndex = content.indexOf('\nflutter:');
    if (flutterIndex >= 0) {
      return '${content.substring(0, flutterIndex)}\n'
          'dev_dependencies:\n$dependency'
          '${content.substring(flutterIndex)}';
    }
    return '$content\ndev_dependencies:\n$dependency';
  }

  List<String> _testsAssetLines(String testsDirRelative) {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    final dirs = <String>{_withTrailingSlash(testsDirRelative)};
    if (testsDir.existsSync()) {
      for (final entity in testsDir.listSync(recursive: true)) {
        if (entity is! File) continue;
        final dir = p.dirname(p.relative(entity.path, from: appDir));
        dirs.add(_withTrailingSlash(p.split(dir).join('/')));
      }
    }
    final sortedDirs = dirs.toList()
      ..sort((a, b) {
        final depthCompare = '/'.allMatches(a).length.compareTo(
              '/'.allMatches(b).length,
            );
        return depthCompare == 0 ? a.compareTo(b) : depthCompare;
      });
    return sortedDirs.map(testsAssetLineFor).toList();
  }

  String? get _testsDirRelative {
    final configFile = File(_ensembleConfigPath);
    if (!configFile.existsSync()) return null;

    final dynamic config = loadYaml(configFile.readAsStringSync());
    if (config is! YamlMap) return null;

    final definitions = config['definitions'];
    if (definitions is! YamlMap) return null;

    final local = definitions['local'];
    if (local is! YamlMap) return null;

    final appPath = local['path']?.toString();
    if (appPath == null || appPath.isEmpty) return null;

    return p.posix.join(_withoutTrailingSlash(appPath), 'tests');
  }

  bool _hasTestYamlOnDisk(String testsDirRelative) {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    if (!testsDir.existsSync()) return false;
    return testsDir
        .listSync(recursive: true)
        .any((entity) => entity.path.endsWith('.test.yaml'));
  }

  static String _activateTestAssets(
    String content,
    String testsDirRelative,
    List<String> testAssetLines,
  ) {
    final normalizedTestsDir = _withTrailingSlash(testsDirRelative);
    final testsAssetLine = testsAssetLineFor(normalizedTestsDir);
    final missingLines = testAssetLines
        .where(
          (line) =>
              !content.contains(line) && !content.contains(line.trimLeft()),
        )
        .toList();
    if (missingLines.isEmpty) {
      return content;
    }
    final insertion = missingLines.join('\n');

    if (content.contains(testsAssetLine)) {
      return content.replaceFirst(
        testsAssetLine,
        '$testsAssetLine\n$insertion',
      );
    }

    final localAppLine =
        '    - ${_withTrailingSlash(p.posix.dirname(_withoutTrailingSlash(normalizedTestsDir)))}\n';
    if (content.contains(localAppLine)) {
      return content.replaceFirst(
        localAppLine,
        '$localAppLine$insertion\n',
      );
    }

    const ensembleDirLine = '    - ensemble/\n';
    if (content.contains(ensembleDirLine)) {
      return content.replaceFirst(
        ensembleDirLine,
        '$ensembleDirLine$insertion\n',
      );
    }

    const assetsMarker = '\n  assets:\n';
    if (content.contains(assetsMarker)) {
      return content.replaceFirst(
        assetsMarker,
        '$assetsMarker$insertion\n',
      );
    }

    throw StateError(
      'Could not patch pubspec.yaml assets: add a flutter.assets section.',
    );
  }

  static String _withTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/') ? normalized : '$normalized/';
  }

  static String _withoutTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/')
        ? normalized.substring(0, normalized.length - 1)
        : normalized;
  }
}
