import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Temporarily wires [appDir] to run declarative YAML tests, then restores files.
class YamlTestAppPatcher {
  YamlTestAppPatcher(String appDir) : appDir = p.normalize(p.absolute(appDir));

  final String appDir;

  static const testEntryRelativePath = 'test/ensemble_tests.dart';
  static String testsAssetLineFor(String testsDirRelative) =>
      '    - ${_withTrailingSlash(testsDirRelative)}';

  /// Legacy CLI stub without module bootstrap.
  static const legacyTestEntryContents = '''
// Generated by ensemble_test_runner — run `dart run ensemble_test_runner:ensemble_test`.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';

void main() => runEnsembleYamlTests();
''';

  static String testEntryContentsFor(String packageName) => '''
// Generated by ensemble_test_runner — customize bootstrap here.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';
import 'package:$packageName/generated/ensemble_modules.dart';

Future<void> main() async {
  await runEnsembleYamlTests(
    bootstrap: () => EnsembleModules().init(),
  );
}
''';

  /// @deprecated Use [testEntryContentsFor].
  static String get testEntryContents =>
      testEntryContentsFor('your_app_package');

  final Map<String, String> _backups = {};
  bool _enabled = false;
  bool _removeTestEntryOnRestore = false;
  bool _pubspecChanged = false;

  bool get pubspecChanged => _pubspecChanged;

  String? get testsDirRelative => _testsDirRelative;

  String? get testsDirPath {
    final relative = testsDirRelative;
    if (relative == null) return null;
    return p.join(appDir, relative);
  }

  bool get hasTestYamlOnDisk {
    final testsDir = testsDirRelative;
    return testsDir != null && _hasTestYamlOnDisk(testsDir);
  }

  String get _pubspecPath => p.join(appDir, 'pubspec.yaml');
  String get _testEntryPath => p.join(appDir, testEntryRelativePath);
  String get _testDirPath => p.join(appDir, 'test');
  String get _ensembleConfigPath =>
      p.join(appDir, 'ensemble', 'ensemble-config.yaml');

  void enable() {
    if (_enabled) return;

    _backup(_pubspecPath);
    _backup(_testEntryPath, optional: true);

    final pubspec = File(_pubspecPath).readAsStringSync();
    final activated = _activatePubspec(pubspec);
    _pubspecChanged = activated != pubspec;
    if (_pubspecChanged) {
      File(_pubspecPath).writeAsStringSync(activated);
    }

    final testEntry = File(_testEntryPath);
    final testEntryExisted = testEntry.existsSync();
    _removeTestEntryOnRestore = !testEntryExisted;

    if (!testEntryExisted) {
      Directory(_testDirPath).createSync(recursive: true);
      testEntry.writeAsStringSync(
        testEntryContentsFor(_readPackageName()),
      );
    } else {
      final content = testEntry.readAsStringSync();
      if (content.trim() == legacyTestEntryContents.trim()) {
        final upgraded = testEntryContentsFor(_readPackageName());
        testEntry.writeAsStringSync(upgraded);
        _backups[_testEntryPath] = upgraded;
        _removeTestEntryOnRestore = false;
      }
    }

    _enabled = true;
  }

  void restore() {
    if (!_enabled) return;

    _restore(_pubspecPath);
    if (_removeTestEntryOnRestore) {
      _deleteTestEntry();
    } else {
      _restore(_testEntryPath);
    }

    _backups.clear();
    _enabled = false;
    _removeTestEntryOnRestore = false;
    _pubspecChanged = false;
  }

  void _backup(String path, {bool optional = false}) {
    final file = File(path);
    if (!file.existsSync()) {
      if (!optional) {
        throw StateError('Expected file not found: $path');
      }
      _backups[path] = '';
      return;
    }
    _backups[path] = file.readAsStringSync();
  }

  void _restore(String path) {
    final backup = _backups[path];
    if (backup == null || backup.isEmpty) return;
    File(path).writeAsStringSync(backup);
  }

  String _readPackageName() {
    final content = File(_pubspecPath).readAsStringSync();
    final match =
        RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(content);
    if (match == null) {
      throw StateError('Could not read package name from pubspec.yaml');
    }
    return match.group(1)!;
  }

  void _deleteTestEntry() {
    final file = File(_testEntryPath);
    if (file.existsSync()) {
      file.deleteSync();
    }
    final testDir = Directory(_testDirPath);
    if (testDir.existsSync() && testDir.listSync().isEmpty) {
      testDir.deleteSync();
    }
  }

  String _activatePubspec(String content) {
    final testsDir = testsDirRelative;
    if (testsDir != null && _hasTestYamlOnDisk(testsDir)) {
      return _activateTestAssets(content, testsDir, _testsAssetLines(testsDir));
    }
    return content;
  }

  List<String> _testsAssetLines(String testsDirRelative) {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    final dirs = <String>{_withTrailingSlash(testsDirRelative)};
    if (testsDir.existsSync()) {
      for (final entity in testsDir.listSync(recursive: true)) {
        if (entity is! File) continue;
        final dir = p.dirname(p.relative(entity.path, from: appDir));
        dirs.add(_withTrailingSlash(p.split(dir).join('/')));
      }
    }
    final sortedDirs = dirs.toList()
      ..sort((a, b) {
        final depthCompare = '/'.allMatches(a).length.compareTo(
              '/'.allMatches(b).length,
            );
        return depthCompare == 0 ? a.compareTo(b) : depthCompare;
      });
    return sortedDirs.map(testsAssetLineFor).toList();
  }

  String? get _testsDirRelative {
    final configFile = File(_ensembleConfigPath);
    if (!configFile.existsSync()) return null;

    final dynamic config = loadYaml(configFile.readAsStringSync());
    if (config is! YamlMap) return null;

    final definitions = config['definitions'];
    if (definitions is! YamlMap) return null;

    final local = definitions['local'];
    if (local is! YamlMap) return null;

    final appPath = local['path']?.toString();
    if (appPath == null || appPath.isEmpty) return null;

    return p.posix.join(_withoutTrailingSlash(appPath), 'tests');
  }

  bool _hasTestYamlOnDisk(String testsDirRelative) {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    if (!testsDir.existsSync()) return false;
    return testsDir
        .listSync(recursive: true)
        .any((entity) => entity.path.endsWith('.test.yaml'));
  }

  static String _activateTestAssets(
    String content,
    String testsDirRelative,
    List<String> testAssetLines,
  ) {
    final normalizedTestsDir = _withTrailingSlash(testsDirRelative);
    final testsAssetLine = testsAssetLineFor(normalizedTestsDir);
    final missingLines = testAssetLines
        .where(
          (line) =>
              !content.contains(line) && !content.contains(line.trimLeft()),
        )
        .toList();
    if (missingLines.isEmpty) {
      return content;
    }
    final insertion = missingLines.join('\n');

    if (content.contains(testsAssetLine)) {
      return content.replaceFirst(
        testsAssetLine,
        '$testsAssetLine\n$insertion',
      );
    }

    final localAppLine =
        '    - ${_withTrailingSlash(p.posix.dirname(_withoutTrailingSlash(normalizedTestsDir)))}\n';
    if (content.contains(localAppLine)) {
      return content.replaceFirst(
        localAppLine,
        '$localAppLine$insertion\n',
      );
    }

    const ensembleDirLine = '    - ensemble/\n';
    if (content.contains(ensembleDirLine)) {
      return content.replaceFirst(
        ensembleDirLine,
        '$ensembleDirLine$insertion\n',
      );
    }

    const assetsMarker = '\n  assets:\n';
    if (content.contains(assetsMarker)) {
      return content.replaceFirst(
        assetsMarker,
        '$assetsMarker$insertion\n',
      );
    }

    throw StateError(
      'Could not patch pubspec.yaml assets: add a flutter.assets section.',
    );
  }

  static String _withTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/') ? normalized : '$normalized/';
  }

  static String _withoutTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/')
        ? normalized.substring(0, normalized.length - 1)
        : normalized;
  }
}
