name: ensemble_dropdown
description: "Accessible Dropdown."
version: 0.0.1
homepage: https://github.com/EnsembleUI/ensemble/modules/ensemble_dropdown


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

