name: ensemble_bluetooth
description: Bluetooth Low Energy scanning and connection support for Ensemble apps.
homepage: https://ensembleui.com
repository: https://github.com/EnsembleUI/ensemble/tree/main/modules/ensemble_bluetooth
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://github.com/EnsembleUI/ensemble/tree/main/modules/ensemble_bluetooth#readme
topics:
  - bluetooth
  - ble
  - low-code
  - ensemble
version: 1.2.48

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  # embed Ensemble as a sibling project
  ensemble:
    git:
      url: https://github.com/EnsembleUI/ensemble.git
      ref: ensemble-v1.2.48-beta.1
      path: modules/ensemble
  ensemble_ts_interpreter: ^1.2.0

  collection: ^1.17.1
  flutter_blue_plus: ^1.33.4
  workmanager: ^0.7.0
  permission_handler: ^11.3.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0