name: ensemble_bracket
description: Tournament bracket widget implementation for Ensemble apps.
homepage: https://ensembleui.com
repository: https://github.com/EnsembleUI/ensemble/tree/main/modules/bracket
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://github.com/EnsembleUI/ensemble/tree/main/modules/bracket#readme
topics:
  - tournament
  - brackets
  - low-code
  - ensemble
platforms:
  android:
  ios:
  macos:
  web:
  windows:

version: 1.2.48

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  ensemble:
    git:
      url: https://github.com/EnsembleUI/ensemble.git
      ref: ensemble-v1.2.48-beta.2
      path: modules/ensemble

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

