name: ensemble_ts_interpreter
description: >-
  A JavaScript (ES5) interpreter written entirely in Dart for Flutter applications.
  Execute JavaScript code inline within your Dart/Flutter app without external engines.
  Features include primitive types, arrays, maps, function declarations, and extensible
  context objects. Perfect for dynamic code execution, user-defined scripts, and
  lightweight JavaScript processing in Flutter apps.
version: 1.0.2

homepage: https://ensembleui.com
repository: https://github.com/EnsembleUI/ensemble/tree/main/modules/ensemble_ts_interpreter
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://pub.dev/documentation/ensemble_ts_interpreter

topics:
  - javascript
  - interpreter
  - es5
  - dart
  - flutter
  - runtime
  - scripting
  - dynamic

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaml: ^3.1.0
  http: ^1.2.1
  json_path: ^0.7.2
  duration: ^3.0.11
  ensemble_date: ^1.6.1
  parsejs_null_safety: ^2.0.4
  source_span: ^1.9.1
  intl: '>=0.17.0 <=0.20.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #assets:
  # - assets/hotel_booking.yaml
  #- assets/basic.yaml
  #- assets/basic_conditionals.yaml

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
