import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Temporarily wires [appDir] to run declarative YAML tests, then restores files.
class YamlTestAppPatcher {
  YamlTestAppPatcher(String appDir) : appDir = p.normalize(p.absolute(appDir));

  final String appDir;

  static const testEntryRelativePath = 'test/ensemble_tests.dart';
  static String testsAssetLineFor(String testsDirRelative) =>
      '    - ${_withTrailingSlash(testsDirRelative)}';

  static const testEntryContents = '''
// Generated by ensemble_test_runner — run `dart run ensemble_test_runner:ensemble_test`.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';

void main() => runEnsembleYamlTests();
''';

  final Map<String, String> _backups = {};
  bool _enabled = false;
  bool _removeTestEntryOnRestore = false;
  bool _pubspecChanged = false;

  bool get pubspecChanged => _pubspecChanged;

  String get _pubspecPath => p.join(appDir, 'pubspec.yaml');
  String get _testEntryPath => p.join(appDir, testEntryRelativePath);
  String get _testDirPath => p.join(appDir, 'test');
  String get _ensembleConfigPath =>
      p.join(appDir, 'ensemble', 'ensemble-config.yaml');

  void enable() {
    if (_enabled) return;

    _backup(_pubspecPath);
    _backup(_testEntryPath, optional: true);

    final priorTestEntry = _backups[_testEntryPath] ?? '';
    _removeTestEntryOnRestore =
        priorTestEntry.isEmpty || priorTestEntry == testEntryContents;

    final pubspec = File(_pubspecPath).readAsStringSync();
    final activated = _activatePubspec(pubspec);
    _pubspecChanged = activated != pubspec;
    if (_pubspecChanged) {
      File(_pubspecPath).writeAsStringSync(activated);
    }

    Directory(_testDirPath).createSync(recursive: true);
    final testEntry = File(_testEntryPath);
    if (!testEntry.existsSync() ||
        testEntry.readAsStringSync() != testEntryContents) {
      testEntry.writeAsStringSync(testEntryContents);
    }

    _enabled = true;
  }

  void restore() {
    if (!_enabled) return;

    _restore(_pubspecPath);
    if (_removeTestEntryOnRestore) {
      _deleteTestEntry();
    } else {
      _restore(_testEntryPath);
    }

    _backups.clear();
    _enabled = false;
    _removeTestEntryOnRestore = false;
    _pubspecChanged = false;
  }

  void _backup(String path, {bool optional = false}) {
    final file = File(path);
    if (!file.existsSync()) {
      if (!optional) {
        throw StateError('Expected file not found: $path');
      }
      _backups[path] = '';
      return;
    }
    _backups[path] = file.readAsStringSync();
  }

  void _restore(String path) {
    final backup = _backups[path];
    if (backup == null || backup.isEmpty) return;
    File(path).writeAsStringSync(backup);
  }

  void _deleteTestEntry() {
    final file = File(_testEntryPath);
    if (file.existsSync()) {
      file.deleteSync();
    }
    final testDir = Directory(_testDirPath);
    if (testDir.existsSync() && testDir.listSync().isEmpty) {
      testDir.deleteSync();
    }
  }

  String _activatePubspec(String content) {
    final testsDir = _testsDirRelative;
    if (testsDir != null && _hasTestYamlOnDisk(testsDir)) {
      return _activateTestAssets(content, testsDir);
    }
    return content;
  }

  String? get _testsDirRelative {
    final configFile = File(_ensembleConfigPath);
    if (!configFile.existsSync()) return null;

    final dynamic config = loadYaml(configFile.readAsStringSync());
    if (config is! YamlMap) return null;

    final definitions = config['definitions'];
    if (definitions is! YamlMap) return null;

    final local = definitions['local'];
    if (local is! YamlMap) return null;

    final appPath = local['path']?.toString();
    if (appPath == null || appPath.isEmpty) return null;

    return p.posix.join(_withoutTrailingSlash(appPath), 'tests');
  }

  bool _hasTestYamlOnDisk(String testsDirRelative) {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    if (!testsDir.existsSync()) return false;
    return testsDir
        .listSync(recursive: true)
        .any((entity) => entity.path.endsWith('.test.yaml'));
  }

  static String _activateTestAssets(String content, String testsDirRelative) {
    final normalizedTestsDir = _withTrailingSlash(testsDirRelative);
    final testsAssetLine = testsAssetLineFor(normalizedTestsDir);
    if (content.contains(testsAssetLine) ||
        content.contains('- $normalizedTestsDir')) {
      return content;
    }

    final localAppLine =
        '    - ${_withTrailingSlash(p.posix.dirname(_withoutTrailingSlash(normalizedTestsDir)))}\n';
    if (content.contains(localAppLine)) {
      return content.replaceFirst(
        localAppLine,
        '$localAppLine$testsAssetLine\n',
      );
    }

    const ensembleDirLine = '    - ensemble/\n';
    if (content.contains(ensembleDirLine)) {
      return content.replaceFirst(
        ensembleDirLine,
        '$ensembleDirLine$testsAssetLine\n',
      );
    }

    const assetsMarker = '\n  assets:\n';
    if (content.contains(assetsMarker)) {
      return content.replaceFirst(
        assetsMarker,
        '$assetsMarker$testsAssetLine\n',
      );
    }

    throw StateError(
      'Could not patch pubspec.yaml assets: add a flutter.assets section.',
    );
  }

  static String _withTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/') ? normalized : '$normalized/';
  }

  static String _withoutTrailingSlash(String path) {
    final normalized = path.replaceAll('\\', '/');
    return normalized.endsWith('/')
        ? normalized.substring(0, normalized.length - 1)
        : normalized;
  }
}
