import 'dart:io';

import 'package:path/path.dart' as p;

/// Temporarily wires [appDir] to run declarative YAML tests, then restores files.
class YamlTestAppPatcher {
  YamlTestAppPatcher(String appDir) : appDir = p.normalize(p.absolute(appDir));

  final String appDir;

  static const testEntryRelativePath = 'test/ensemble_tests.dart';
  static const testsAssetLine = '    - ensemble/tests/';
  static const testsDirRelative = 'ensemble/tests';

  static const testEntryContents = '''
// Generated by ensemble_test_runner — run `dart run ensemble_test_runner:ensemble_test`.
import 'package:ensemble_test_runner/entry/ensemble_test_entry.dart';

void main() => runEnsembleYamlTests();
''';

  final Map<String, String> _backups = {};
  bool _enabled = false;
  bool _removeTestEntryOnRestore = false;
  bool _pubspecChanged = false;

  bool get pubspecChanged => _pubspecChanged;

  String get _pubspecPath => p.join(appDir, 'pubspec.yaml');
  String get _testEntryPath => p.join(appDir, testEntryRelativePath);
  String get _testDirPath => p.join(appDir, 'test');

  void enable() {
    if (_enabled) return;

    _backup(_pubspecPath);
    _backup(_testEntryPath, optional: true);

    final priorTestEntry = _backups[_testEntryPath] ?? '';
    _removeTestEntryOnRestore =
        priorTestEntry.isEmpty || priorTestEntry == testEntryContents;

    final pubspec = File(_pubspecPath).readAsStringSync();
    final activated = _activatePubspec(pubspec);
    _pubspecChanged = activated != pubspec;
    if (_pubspecChanged) {
      File(_pubspecPath).writeAsStringSync(activated);
    }

    Directory(_testDirPath).createSync(recursive: true);
    final testEntry = File(_testEntryPath);
    if (!testEntry.existsSync() ||
        testEntry.readAsStringSync() != testEntryContents) {
      testEntry.writeAsStringSync(testEntryContents);
    }

    _enabled = true;
  }

  void restore() {
    if (!_enabled) return;

    _restore(_pubspecPath);
    if (_removeTestEntryOnRestore) {
      _deleteTestEntry();
    } else {
      _restore(_testEntryPath);
    }

    _backups.clear();
    _enabled = false;
    _removeTestEntryOnRestore = false;
    _pubspecChanged = false;
  }

  void _backup(String path, {bool optional = false}) {
    final file = File(path);
    if (!file.existsSync()) {
      if (!optional) {
        throw StateError('Expected file not found: $path');
      }
      _backups[path] = '';
      return;
    }
    _backups[path] = file.readAsStringSync();
  }

  void _restore(String path) {
    final backup = _backups[path];
    if (backup == null || backup.isEmpty) return;
    File(path).writeAsStringSync(backup);
  }

  void _deleteTestEntry() {
    final file = File(_testEntryPath);
    if (file.existsSync()) {
      file.deleteSync();
    }
    final testDir = Directory(_testDirPath);
    if (testDir.existsSync() && testDir.listSync().isEmpty) {
      testDir.deleteSync();
    }
  }

  String _activatePubspec(String content) {
    if (_hasTestYamlOnDisk) {
      return _activateTestAssets(content);
    }
    return content;
  }

  bool get _hasTestYamlOnDisk {
    final testsDir = Directory(p.join(appDir, testsDirRelative));
    if (!testsDir.existsSync()) return false;
    return testsDir
        .listSync()
        .any((entity) => entity.path.endsWith('.test.yaml'));
  }

  static String _activateTestAssets(String content) {
    if (content.contains(testsAssetLine) ||
        content.contains('- ensemble/tests/')) {
      return content;
    }

    const ensembleDirLine = '    - ensemble/\n';
    if (content.contains(ensembleDirLine)) {
      return content.replaceFirst(
        ensembleDirLine,
        '$ensembleDirLine$testsAssetLine\n',
      );
    }

    const assetsMarker = '\n  assets:\n';
    if (content.contains(assetsMarker)) {
      return content.replaceFirst(
        assetsMarker,
        '$assetsMarker$testsAssetLine\n',
      );
    }

    throw StateError(
      'Could not patch pubspec.yaml assets: add a flutter.assets section.',
    );
  }
}
