name: ensemble_face_camera
description: A standalone face detection camera module for Ensemble.
homepage: https://ensembleui.com
repository: https://github.com/EnsembleUI/ensemble
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://github.com/EnsembleUI/ensemble/tree/main/modules/face_camera#readme
topics:
  - face-detection
  - camera
  - low-code
  - ensemble
platforms:
  android:
  ios:
  web:
version: 1.2.49

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  camera: ^0.11.0+2
  face_camera: ^0.1.4
  ensemble:
    git:
      url: https://github.com/EnsembleUI/ensemble.git
      ref: ensemble-v1.2.49
      path: modules/ensemble
  ensemble_ts_interpreter: ^1.2.0
  collection: ^1.17.1
  image_picker: ^0.8.7+5
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - web/face_api.js
    - web/face_detection.js
