name: parsejs_null_safety
version: 2.0.3
description: >-
  JavaScript parser originally written by Asger Feldthaus<asger.feldthaus@gmail.com>
  Upgraded to Dart 2.12 with null safety.

homepage: https://github.com/EnsembleUI/ensemble
repository: https://github.com/EnsembleUI/ensemble/tree/main/modules/parsejs_null_safety
issue_tracker: https://github.com/EnsembleUI/ensemble/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  unicode: '>=0.0.8 <1.0.0'
