name: ensemble_adobe_analytics
description: Adobe Analytics integration for Ensemble
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ensemble:
    git:
      url: https://github.com/EnsembleUI/ensemble.git
      ref: ensemble-v1.1.67
      path: modules/ensemble

  flutter_aepcore: ^5.0.0
  flutter_aepedge: ^5.0.0
  flutter_aepassurance: ^5.0.0
  flutter_aepedgeidentity: ^5.0.0
  flutter_aepedgeconsent: ^5.0.0
  flutter_aepuserprofile: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
