name: ensemble_table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter with enhanced overlay ranges, tooltips, and marking capabilities. A maintained fork with additional features.
version: 3.1.2
# Remove deprecated author field - will use publishers in pub.dev
homepage: https://ensembleui.com/
repository: https://github.com/EnsembleUI/ensemble
issue_tracker: https://github.com/EnsembleUI/ensemble/issues
documentation: https://github.com/EnsembleUI/ensemble/tree/main/packages/table_calendar#readme

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.18.1 <=0.20.2"
  simple_gesture_detector: ^0.2.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
