name: high_chart
description: A chart library based on High Charts (.JS), able to build advanced
  charts like Pie chart, linear chart, etc.
version: 2.0.2
homepage: https://github.com/senthilnasa/high_chart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  url_launcher: ^6.0.18
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.senthilnasa.high_chart
        pluginClass: HighChartPlugin
      ios:
        pluginClass: HighChartPlugin
      web:
        pluginClass: HighChartPlatformInterface
        fileName: high_chart_web.dart
