name: Build Ensemble
on:
  workflow_dispatch:
    
#   pull_request:
#     types: [opened, reopened]

jobs:
  buildAndTest:
  
    runs-on: macos-12
    steps:
    
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
    
      - name: Pub Upgrade
        run: flutter pub upgrade
      
      - name: Unit Tests / Widget Tests 
        run: flutter test
