name: Execute Tests
on:
  workflow_dispatch:

#   pull_request:
#     types: [opened, reopened]

jobs:
  test:
    name: Execute Tests
  
    runs-on: macos-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Pub Upgrade
      run: flutter pub upgrade

    - name: Run Unit Tests / Widget Tests
      run: flutter test
      
    - name: Start iOS Simulator
      uses: futureware-tech/simulator-action@v2
      with:
        model: 'iPhone 14 Pro Max'
        shutdown_after_job: true
        
    - name: List all simulators
      run: "xcrun xctrace list devices"
        
    - name: Run Integration Tests
      run: flutter test integration_test --verbose
  

    
    
