name: Create Release on Tag

on:
  push:
    tags:
      - "ensemble-v*"

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, '-beta')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
